### ISSUE TITLE
different cache sizes for fdroid

### ISSUE THREAD

**Issue by Clevero** [Frozen-Developers/android-cache-cleaner#19]
just installed the new Version via fdroid. for fdroid itself cachecleaner shows me 9,7MB. after clicking the froid entry "App-Info" shows me after calculating 36,79MB. Is this a bug or is there a understanding problem on my side?

**Comment by Kuci** [comment]
Hello @Clevero, thank you for reporting the issue.

I took a look at the issue and I have found out we were not considering external cache, which is only available in Honeycomb and newer. This should be fixed in the next release.

**Comment by Clevero** [comment]
Thanks :D
