### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by Kuci** [Frozen-Developers/android-cache-cleaner#20]
French, Portuguese and Serbian translations needs to be update. @RyDroid, @smarquespt and @pejakm, please, could you take care of it, guys ?

**Comment by pejakm** [comment]
- [ ] French
- [ ] Portuguese
- [x] Serbian

**Comment by Kuci** [comment]
Thank you, @pejakm, for the good job.

**Comment by Kuci** [comment]
Thank you, @RyDroid, for updated French translation.

**Comment by Kuci** [comment]
@smarquespt, please, try to update Portuguese translation as soon as possible.

**Comment by smarquespt** [comment]
@Kuci 

I no longer have git im my computer, but you can grab the file in http://ge.tt/2ZRinCQ2/v/0

**Comment by Kuci** [comment]
@smarquespt The link is dead.

**Comment by smarquespt** [comment]
@Kuci 

Can you please try again? Hopefully the link is fixed.

**Comment by Kuci** [comment]
Thank you @smarquespt, I got it now. But I see you have missed ```toast_could_not_clean``` string, could you translate this one as well, please ?

**Comment by smarquespt** [comment]
I really missed it. Sorry. [Here it is](http://ge.tt/3vHiGHQ2/v/0)

**Comment by Kuci** [comment]
Thank you @smarquespt, it seems like we are done here.

Thank you guys for pulling this off, I really appreciate that.
