### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by Kuci** [Frozen-Developers/android-cache-cleaner#26]
Once again, translations need to be updated. @RyDroid, @smarquespt and @pejakm, please, update the translations or leave a comment if you can not do so. 

Status: 
- [X] French 
- [x] Portuguese 
- [x] Serbian

**Comment by Kuci** [comment]
@smarquespt, this is the last one before 2.2.0 release. Please, will you do it ? Let me know even if you are not going to do it.

**Comment by smarquespt** [comment]
Sorry for late reply. Here(http://ge.tt/5YEaT4R2/v/0) it is.

**Comment by Kuci** [comment]
Thank you guys for doing this once again.
