### ISSUE TITLE
[feature-request] option for total amount of cache cleaned

### ISSUE THREAD

**Issue by revuwa** [Frozen-Developers/android-cache-cleaner#31]
> The app no longer reports the total amount of cache cleaned because of multiple reasons.

I don't know if I understand the reasons correctly. But:
* the app seems to work (on my i9100 @ AOSP 4.2.2);
* the single apps under 'App cache used' showing sizes, which going down after a cache cleaning, for example from 4MB to 12KB.

Because I'm really missing that amount feature since the latest v2.2.0 version, I kindly wanted to ask, if you probably would provide that feature as an option again, (e. g. on Android versions <= 5.0, or tagged with 'buggy', or forced linked with the 'scanning before cleaning' option). But it would be so great if you would bring some (for my sake slightly inaccurate) numbers back to the cleaning toast, please.

**Comment by krBlackCat** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

isl2121@naver.com 님께 보내신 메일 <[android-cache-cleaner] [feature-request] option for total amount of cache cleaned (#31)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by Kuci** [comment]
Hello, @revuwa.

If you refer to one of my comments from #30, then yes, I could bring it back, but if you reread the whole #30 you will see that we can do pretty much nothing about accuracy of the number and I am not really sure why would we want to show a potentially totally inaccurate number. I would rather let the user find out on his own what is the real difference if he is interested.

**Comment by krBlackCat** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

isl2121@naver.com 님께 보내신 메일 <Re: [android-cache-cleaner] [feature-request] option for total amount of cache cleaned (#31)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by revuwa** [comment]
Thanks for your response.

Oops! Seems I overread the important sections of the refered https://github.com/Frozen-Developers/android-cache-cleaner/issues/30. Sorry for that.
Furthermore it seems I have to put up with losing the (the absolutely inaccurate) numbers...
