### ISSUE TITLE
Schedule interval for cleaning

### ISSUE THREAD

**Issue by reddit-is-fun** [Frozen-Developers/android-cache-cleaner#32]
Instead of cleaning the cache on boot, it would be preferred to set an interval instead (once a week for example). I usually prevent apps from running when the system boots.  
There should be a setting that allows user to choose when to clear cache.

**Comment by Kuci** [comment]
Hi @reddit-is-fun,

Sure, having such a feat

**Comment by Kuci** [comment]
Hi, @reddit-is-fun.

First of all I'm sorry for accidentally closing this issue prematurely.

Sure, having such a feature would be nice and I feel like it has already been requested multiple times. Well, the main reasons why the feature is not present are:
* I don't need it
* I don't have time for implementing it
* We wanted to keep the app as lightweight as possible

But I will leave this issue opened, just in case somebody else would like to implement it.

**Comment by reddit-is-fun** [comment]
@Kuci Since I'm not a programmer, I don't know how much work adding that feature is. Hopefully you can see that there's demand for it. 
I doubt that the setting would require significantly more resources. Google's Material Design isn't the most lightweight UI option either?

**Comment by reddit-is-fun** [comment]
I close this issue after hearing Android 6 news.
