### ISSUE TITLE
Cache cleaner not clearing datas in marshmallow

### ISSUE THREAD

**Issue by TakeoffAndroid** [Frozen-Developers/android-cache-cleaner#33]
The caches are not clearing in marshmallow, whereas Clean Master is clearing the caches. Kindly please help me regarding this and do provide support for marshmallow

**Comment by Kuci** [comment]
Hi, @TakeoffAndroid.

Please read [this](https://github.com/Frozen-Developers/android-cache-cleaner#partial-incompatibility-with-android-60-and-newer). Clean Master does not work for me either.

**Comment by TakeoffAndroid** [comment]
Clean Master is working fine for me in marshmallow. They are using
accessibility service for it.

**Comment by Kuci** [comment]
Do you know any technical details ?

**Comment by TakeoffAndroid** [comment]
I don't know. What about you?

**Comment by Kuci** [comment]
Neither I do. I will take a look at it, but right now I'm too busy.

**Comment by Kuci** [comment]
Well, it seems like the problem has solved itself. Checkout out `Deprecation` section in README.

**Comment by bhavikgandhi007** [comment]
can you suggest any library for advertise cache clean in marshmallow?
