### ISSUE TITLE
FR: List of exclusion

### ISSUE THREAD

**Issue by ThecaTTony** [Frozen-Developers/android-cache-cleaner#34]
Hi, this is a feature request, no a bug.

Can you include a list of exclusion? So the apps listed cache is not deleted.
It would be useful for applications such as MPDroid, who tend to maintain in cache the album covers

Thanks.

**Comment by Kuci** [comment]
Hey @ThecaTTony, thank you for the suggestion !

Unfortunately, we have pretty much no control over cleaning of the internal memory - Android does it itself. What we do have control over is cleaning of the external memory, but implementing the feature for externally cached apps only may cause confusion among our users, so I'm afraid of that I'll have to reject your suggestion.

**Comment by Gitoffthelawn** [comment]
I might be misreading this, but I think you may be misunderstanding @ThecaTTony.  I think they are referring to cleaning external memory, and allowing exceptions for certain apps.  That said, IIRC, the method by which this app cleans the memory does not allow exceptions, as it is does not target cleaning of specific apps, but instead, the overall cache space.

I think @ThecaTTony 's idea is a very useful one.  But I don't think it could be done with how this app currently works.

**Comment by Kuci** [comment]
You have misread that, @Gitoffthelawn. The idea is good (even though it might be in conflict with our principles of simplicity), but we cannot fully implement it.

**Comment by ThecaTTony** [comment]
Thanks anyway.
