### ISSUE TITLE
[FR] sort by full size

### ISSUE THREAD

**Issue by ildar** [Frozen-Developers/android-cache-cleaner#35]
It would be nice to have an option to sort by full size.
Sometimes a whole app can be irrelevant like a cache :)

**Comment by Kuci** [comment]
What do you mean by "full size" ?

**Comment by ildar** [comment]
Full app size including apk and data

пн, 15 февр. 2016, 17:34, Ľubomír Kučera <notifications@github.com>:

> What do you mean by "full size" ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Frozen-Developers/android-cache-cleaner/issues/35#issuecomment-184175827>
> .
>
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by Kuci** [comment]
Honestly, I see no point in implementing this feature. App or data size is not relevant when it comes to cache cleaning.
