### ISSUE TITLE
Add a confirm popup before cleaning

### ISSUE THREAD

**Issue by M2ck** [Frozen-Developers/android-cache-cleaner#45]

**Comment by Kuci** [comment]
Why ? I don't think it's necessary.

**Comment by M2ck** [comment]
For mimic stock Android feature. Maybe add it as an option.

**Comment by Kuci** [comment]
Yeah, I see. But adding such a thing as an option isn't a good idea. We'll either leave it as is or add it for everyone. Why ? Consistency and an effort to keep it as simple as possible, without more unnecessary settings. If you really think we should implement this, then please, write your arguments for doing so. I think that this is a good idea in stock Settings app, which is available to all types of users. Yet in apps like this one, which targets more advanced users, the users might feel like being slowed down by an unimportant dialog.

**Comment by Kuci** [comment]
@M2ck, are you gonna comment on this ?

**Comment by M2ck** [comment]
Yep you're right, it's not a big deal anyway!

Sorry for the late reply.
